### ISSUE TITLE
TLF support in TG

### ISSUE THREAD

**Issue by hummelstrand** [CasparCG/Tools#1]
The TG can't be used in many areas, since it doesn't support TLF fields. Israel, Bangladesh, India and many other countries can't use CasparCG because templates with correct text for the language can't be created.

**Comment by silid** [comment]
TLF has been deprecated and is not available in Animate CC.

**Comment by jesperstarkar** [comment]
Just for clearification: The TLF framework is supported and can be used standalone. But we can't make any magic happen in TG since this all works runtime as a library.
